### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <    cordova.js:1

### ISSUE THREAD

**Issue by chasebank** [dekimasoon/vue-cli-plugin-cordova#14]
Any ideas why I'd be getting this in a browser?

`Uncaught SyntaxError: Unexpected token <    cordova.js:1 `

This is after running `npm run cordova-serve`. Followed setup instructions perfectly, twice. There has been no modifications made to the project.

I have Cordova running successfully in other projects.

**Comment by dekimasoon** [comment]
hi @chasebank.
Sounds like a plugin's bug. I'll check your issue tonight.
Sorry for your inconvenience.

Somehow `cordova.js` is loaded which isn't existed on that path, then webpack-dev-sever returns `index.html` and SyntaxError occurred because of `index.html` is not js.
It is really helps me to provide the reproduce repo if you could.

**Comment by dekimasoon** [comment]
I'm sorry for the late reply.
I found that if you use this plugin on Windows, symlinks to load cordova.js properly are not made on invoking while if you run command without the admin authority.

Could you check if there are symlinks named `cordova` and `config.xml` in the public directory?
If there aren't, please try `$ vue add cordova` as admin.
if there are, please give me more details 🙏
