### ISSUE TITLE
How does the config symlink work?

### ISSUE THREAD

**Issue by chasebank** [dekimasoon/vue-cli-plugin-cordova#20]
I'm having difficulty getting `cordova-plugin-file` working, and while investigating I noticed that I have a main config in the root directory, and a symlink in public.

Admittedly I'm not experienced with symlinks, but I'd expect there to be no difference between the two files, since they are in fact the same?

However when I open the config in public, it does not match the config in root. Newly installed plugins and configurations are only added to the root config, and do not show in the public one.

Is this the expected behavior?

**Comment by dekimasoon** [comment]
I have made a sample repository about a month ago.
https://github.com/dekimasoon/vue-cli-plugin-cordova/issues/18#issuecomment-397941997

As you can see, config.xml symlink in public dir is not link for root config.xml.
It points to `../platforms/browser/www/config.xml` which is config.xml for browser platform.
https://github.com/dekimasoon/vue-cordova-file-plugin-sample/blob/master/public/config.xml

Your problem seems to have occurred because config.xml is not updated somehow.
I assume that on Windows we need to excute `$cordova build browser` after installing cordova plugins to update `./platforms/browser/www/config.xml`.

Hope it helps you.

**Comment by dekimasoon** [comment]
@chasebank any updates? Please let me know.
